name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy index.html to Dev EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          source: "index.html"
          target: "/home/ubuntu/"

      - name: Move file to Nginx folder
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            sudo cp /home/ubuntu/index.html /var/www/html/index.html
            echo "✅ Deployed to DEV successfully!"
