name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to Dev EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          source: "index.html,Dockerfile"
          target: "/home/ubuntu/"

      - name: Build and Run Docker on Dev EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/ubuntu
            docker stop portfolio || true
            docker rm portfolio || true
            docker build -t my-portfolio:latest .
            docker run -d -p 80:80 --name portfolio my-portfolio:latest
            echo "✅ Dev deployment successful!"
